[project]
name = "clicker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-settings>=2.12.0",
    "pyautogui>=0.9.54",
    "opencv-python>=4.13.0.90",
]
